import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const db=new PGlite();
const config=(metric='median', extra={})=>({current_start:'2025-09',current_end:'2025-09',base_start:'2025-08',base_end:'2025-08',trend_start:'2025-08',history_start:'2025-03',end_month:'2025-09',window:2,metric,district:'全部',business_area:'全部',rooms:'全部',area_min:10,area_max:500,min_current:0,min_base:0,min_total:0,min_active_months:0,...extra});
const history={communities:[['甲区','甲商圈','旧甲'],['乙区','乙商圈','旧乙']],rows:[['2025-08',0,80,100,10,.01,'2'],['2025-08',0,90,300,12,.02,'2'],['2025-08',1,80,1000,9,.03,'3'],['2025-07',0,80,50,8,.01,'2']]};
before(async()=>{await db.exec('create role anon; create role authenticated; create role service_role; create schema housing_private; create table housing_private.communities(id bigint primary key,district text,business_area text,community text); create table housing_private.transactions(id bigint primary key,community_id bigint,sale_date date,area double precision,unit_price double precision,sale_price double precision,listing_price double precision,layout text,rooms text,orientation text,floor text,cycle_days int,discount_rate double precision);');await db.exec(await readFile(new URL('../supabase/migrations/202609220008_market_compute.sql',import.meta.url),'utf8'));await db.exec("insert into housing_private.communities values(1,'甲区','甲商圈','新甲'),(2,'乙区','乙商圈','新乙'); insert into housing_private.transactions values(1,1,'2025-09-01',80,200,1,null,null,'2',null,null,10,.01),(2,1,'2025-09-02',90,400,1,null,null,'2',null,null,12,.02),(3,2,'2025-09-01',80,2000,1,null,null,'3',null,null,9,.03);");});
after(()=>db.close());
async function run(c){return (await db.query('select housing_private.compute_market($1,$2) result',[JSON.stringify(c),JSON.stringify(history)])).rows[0].result;}
test('all exact metrics and the private/free cutoff are combined',async()=>{const expected={mean:[866.666667,466.666667],median:[400,300],p30:[320,220],p60:[720,440],min:[200,100],max:[2000,1000]};for(const [metric,[current,base]] of Object.entries(expected)){const out=await run(config(metric));assert.equal(out.benchmark.current_price,current,metric);assert.equal(out.benchmark.base_price,base,metric);}});
test('benchmark and map ignore selected district, while rankings and trends are scoped',async()=>{const out=await run(config('median',{district:'甲区'}));assert.equal(out.benchmark.current_price,400);assert.deepEqual(out.districts.map(x=>x.district),['甲区']);assert.equal(out.trends['全部'].points.at(-1).volume,2);assert.equal(out.trends['乙区'],undefined);assert.equal(out.map.find(x=>x.district==='乙区').current_volume,1);});
test('candidate arrays retain ineligible rows and 48-month trend uses window pre-roll',async()=>{const out=await run(config('median',{min_current:2,min_base:2,min_total:5}));assert.equal(out.communities.length,4);assert.ok(out.communities.every(x=>x.eligible===false));const p=out.trends['全部'].points.find(x=>x.month==='2025-08');assert.equal(p.window_volume,4);assert.equal(out.trends['全部'].points.length,48);});
test('empty filters return a stable zero-volume benchmark instead of a null report',async()=>{const out=await run(config('median',{rooms:'不存在'}));assert.equal(out.benchmark.current_price,null);assert.equal(out.benchmark.current_volume,0);assert.equal(out.districts.length,0);assert.equal(out.map.length,0);});
test('wrapper is service-role-only in the database ACL',async()=>{const acl=(await db.query("select proacl::text acl from pg_proc where proname='housing_compute_market'")).rows[0].acl;assert.match(acl,/service_role=X/);assert.doesNotMatch(acl,/anon=X|authenticated=X/);});
