-- Trusted, pure report computation. p_history is the edge-verified public
-- snapshot: {communities:[[district,business_area,community]],rows:[[YYYY-MM,index,area,price,cycle,discount,rooms]]}.
create or replace function housing_private.compute_market(p_config jsonb,p_history jsonb) returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare out jsonb;
begin
  with recursive cfg as (
    select p_config raw,p_config->>'current_start' cs,p_config->>'current_end' ce,p_config->>'base_start' bs,p_config->>'base_end' be,
      coalesce((p_config->>'window')::int,6) win,coalesce(p_config->>'metric','median') metric,
      coalesce(p_config->>'district','全部') cfg_district,coalesce(p_config->>'business_area','全部') ba,coalesce(p_config->>'rooms','全部') rooms,
      coalesce((p_config->>'area_min')::float8,0) amin,coalesce((p_config->>'area_max')::float8,1e100) amax,
      coalesce((p_config->>'min_current')::int,0) minc,coalesce((p_config->>'min_base')::int,0) minb,coalesce((p_config->>'min_total')::int,0) mint,coalesce((p_config->>'min_active_months')::int,0) minm
  ), b as (
    select cfg.*,greatest('2018-04',to_char(to_date(ce||'-01','YYYY-MM-DD')-interval '47 months','YYYY-MM')) trend_start from cfg
  ), bounds as (
    select b.*,least(bs,cs,to_char(to_date(trend_start||'-01','YYYY-MM-DD')-make_interval(months=>win-1),'YYYY-MM')) history_start,greatest(ce,be) history_end from b
  ), catalog as (
    select ordinality-1 idx,v->>0 district,v->>1 business_area,v->>2 community from jsonb_array_elements(coalesce(p_history->'communities','[]'::jsonb)) with ordinality e(v,ordinality)
  ), pub as (
    select v->>0 sale_month,c.district,c.business_area,c.community,(v->>2)::float8 area,(v->>3)::float8 price,nullif(v->>4,'null')::int cycle,nullif(v->>5,'null')::float8 discount,nullif(v->>6,'null') rooms
    from jsonb_array_elements(coalesce(p_history->'rows','[]'::jsonb)) r(v) join catalog c on c.idx=(v->>1)::int where v->>0<='2025-08'
  ), priv as (
    select to_char(t.sale_date,'YYYY-MM') sale_month,c.district,c.business_area,c.community,t.area,t.unit_price price,t.cycle_days cycle,t.discount_rate discount,t.rooms
    from housing_private.transactions t join housing_private.communities c on c.id=t.community_id where t.sale_date>=date '2025-09-01'
  ), all_rows as (select * from pub union all select * from priv), period_rows as (
    select r.* from all_rows r cross join bounds x where r.sale_month between x.history_start and x.history_end and r.area between x.amin and x.amax and (x.rooms='全部' or r.rooms=x.rooms)
  ), scoped as (select r.* from period_rows r cross join bounds x where (x.cfg_district='全部' or r.district=x.cfg_district) and (x.ba='全部' or r.business_area=x.ba)),
  compare_rows as (select s.* from scoped s cross join bounds x where s.sale_month between x.cs and x.ce or s.sale_month between x.bs and x.be),
  global_compare_rows as (select r.* from period_rows r cross join bounds x where r.sale_month between x.cs and x.ce or r.sale_month between x.bs and x.be),
  ag as (
    select 'district' kind,district,null::text business_area,null::text community,
      round((case when metric='mean' then avg(price) filter(where sale_month between cs and ce) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between cs and ce) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between cs and ce) when metric='min' then min(price) filter(where sale_month between cs and ce) when metric='max' then max(price) filter(where sale_month between cs and ce) else percentile_cont(.5) within group(order by price) filter(where sale_month between cs and ce) end)::numeric,6)::float8 cp,
      round((case when metric='mean' then avg(price) filter(where sale_month between bs and be) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between bs and be) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between bs and be) when metric='min' then min(price) filter(where sale_month between bs and be) when metric='max' then max(price) filter(where sale_month between bs and be) else percentile_cont(.5) within group(order by price) filter(where sale_month between bs and be) end)::numeric,6)::float8 bp,
      count(*) filter(where sale_month between cs and ce)::int cv,count(*) filter(where sale_month between bs and be)::int bv,count(distinct sale_month) filter(where sale_month between cs and ce)::int cm,count(distinct sale_month) filter(where sale_month between bs and be)::int bm,
      round(percentile_cont(.5) within group(order by area) filter(where sale_month between cs and ce)::numeric,6)::float8 ca,round(percentile_cont(.5) within group(order by area) filter(where sale_month between bs and be)::numeric,6)::float8 ba_area,round(percentile_cont(.5) within group(order by cycle) filter(where sale_month between cs and ce)::numeric,6)::float8 cc,round(percentile_cont(.5) within group(order by cycle) filter(where sale_month between bs and be)::numeric,6)::float8 bc,round(percentile_cont(.5) within group(order by discount) filter(where sale_month between cs and ce)::numeric,6)::float8 cd,round(percentile_cont(.5) within group(order by discount) filter(where sale_month between bs and be)::numeric,6)::float8 bd
    from compare_rows cross join bounds group by district,metric,cs,ce,bs,be
    union all
    select 'community',district,business_area,community,
      round((case when metric='mean' then avg(price) filter(where sale_month between cs and ce) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between cs and ce) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between cs and ce) when metric='min' then min(price) filter(where sale_month between cs and ce) when metric='max' then max(price) filter(where sale_month between cs and ce) else percentile_cont(.5) within group(order by price) filter(where sale_month between cs and ce) end)::numeric,6)::float8,
      round((case when metric='mean' then avg(price) filter(where sale_month between bs and be) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between bs and be) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between bs and be) when metric='min' then min(price) filter(where sale_month between bs and be) when metric='max' then max(price) filter(where sale_month between bs and be) else percentile_cont(.5) within group(order by price) filter(where sale_month between bs and be) end)::numeric,6)::float8,
      count(*) filter(where sale_month between cs and ce)::int,count(*) filter(where sale_month between bs and be)::int,count(distinct sale_month) filter(where sale_month between cs and ce)::int,count(distinct sale_month) filter(where sale_month between bs and be)::int,
      round(percentile_cont(.5) within group(order by area) filter(where sale_month between cs and ce)::numeric,6)::float8,round(percentile_cont(.5) within group(order by area) filter(where sale_month between bs and be)::numeric,6)::float8,round(percentile_cont(.5) within group(order by cycle) filter(where sale_month between cs and ce)::numeric,6)::float8,round(percentile_cont(.5) within group(order by cycle) filter(where sale_month between bs and be)::numeric,6)::float8,round(percentile_cont(.5) within group(order by discount) filter(where sale_month between cs and ce)::numeric,6)::float8,round(percentile_cont(.5) within group(order by discount) filter(where sale_month between bs and be)::numeric,6)::float8
    from compare_rows cross join bounds group by district,business_area,community,metric,cs,ce,bs,be
  ), glob as (
    select round((case when metric='mean' then avg(price) filter(where sale_month between cs and ce) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between cs and ce) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between cs and ce) when metric='min' then min(price) filter(where sale_month between cs and ce) when metric='max' then max(price) filter(where sale_month between cs and ce) else percentile_cont(.5) within group(order by price) filter(where sale_month between cs and ce) end)::numeric,6)::float8 cp,round((case when metric='mean' then avg(price) filter(where sale_month between bs and be) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between bs and be) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between bs and be) when metric='min' then min(price) filter(where sale_month between bs and be) when metric='max' then max(price) filter(where sale_month between bs and be) else percentile_cont(.5) within group(order by price) filter(where sale_month between bs and be) end)::numeric,6)::float8 bp,count(price) filter(where sale_month between cs and ce)::int cv,count(price) filter(where sale_month between bs and be)::int bv,round(percentile_cont(.5) within group(order by area) filter(where sale_month between cs and ce)::numeric,6)::float8 ca,round(percentile_cont(.5) within group(order by area) filter(where sale_month between bs and be)::numeric,6)::float8 ba
    from bounds left join global_compare_rows on true group by metric,cs,ce,bs,be
  ), benchmark as (select jsonb_build_object('current_price',cp,'base_price',bp,'price_change',case when bp<>0 then round((cp/bp-1)::numeric,6) end,'current_volume',cv,'base_volume',bv,'volume_change',case when bv<>0 then round((cv::float8/bv-1)::numeric,6) end,'current_area',ca,'base_area',ba) value from glob),
  calc as (select a.*,coalesce(cv,0)+coalesce(bv,0) tv,case when cp is not null and bp<>0 then round((cp/bp-1)::numeric,6)::float8 end change,(coalesce(cv,0)>=minc and coalesce(bv,0)>=minb and coalesce(cv,0)+coalesce(bv,0)>=mint and coalesce(cm,0)>=minm and coalesce(bm,0)>=minm and cp is not null and bp is not null and bp<>0) eligible from ag a cross join bounds),
  resil as (select district,count(*) filter(where eligible) cnt,count(*) filter(where eligible and change>(select (value->>'price_change')::float8 from benchmark)) good from calc where kind='community' group by district),
  records as (select kind,jsonb_build_object('district',district,'business_area',business_area,'community',community,'current_price',cp,'base_price',bp,'price_change',change,'current_volume',cv,'base_volume',bv,'total_volume',tv,'current_months',cm,'base_months',bm,'current_area',ca,'base_area',ba_area,'area_change',case when ba_area<>0 then round((ca/ba_area-1)::numeric,6) end,'current_cycle',cc,'base_cycle',bc,'cycle_change',case when bc<>0 then round((cc/bc-1)::numeric,6) end,'current_discount',cd,'base_discount',bd,'discount_change',case when cd is not null and bd is not null then round((cd-bd)::numeric,6) end,'volume_change',case when bv<>0 then round((cv::float8/bv-1)::numeric,6) end,'relative_beijing',case when change is not null and (select value->>'price_change' from benchmark) is not null then round((change-(select (value->>'price_change')::float8 from benchmark))::numeric,6) end,'eligible',eligible,'resilient_ratio',case when kind='district' and r.cnt>0 then round((r.good::float8/r.cnt)::numeric,6) end,'eligible_community_count',case when kind='district' then coalesce(r.cnt,0) end) value from calc a left join resil r using(district)),
  map_ag as (select case when district='开发区' then '大兴' else district end district,round((case when metric='mean' then avg(price) filter(where sale_month between cs and ce) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between cs and ce) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between cs and ce) when metric='min' then min(price) filter(where sale_month between cs and ce) when metric='max' then max(price) filter(where sale_month between cs and ce) else percentile_cont(.5) within group(order by price) filter(where sale_month between cs and ce) end)::numeric,6)::float8 cp,round((case when metric='mean' then avg(price) filter(where sale_month between bs and be) when metric='p30' then percentile_cont(.3) within group(order by price) filter(where sale_month between bs and be) when metric='p60' then percentile_cont(.6) within group(order by price) filter(where sale_month between bs and be) when metric='min' then min(price) filter(where sale_month between bs and be) when metric='max' then max(price) filter(where sale_month between bs and be) else percentile_cont(.5) within group(order by price) filter(where sale_month between bs and be) end)::numeric,6)::float8 bp,count(*) filter(where sale_month between cs and ce)::int cv,count(*) filter(where sale_month between bs and be)::int bv from global_compare_rows cross join bounds group by 1,metric,cs,ce,bs,be),
  keys as (select '全部' key union select distinct district from scoped), months as (select k.key,to_char(m,'YYYY-MM') sale_month from keys k cross join bounds x cross join lateral generate_series(to_date(x.trend_start||'-01','YYYY-MM-DD'),to_date(x.ce||'-01','YYYY-MM-DD'),'1 month') m), points as (select q.key,q.sale_month,jsonb_build_object('month',q.sale_month,'price',round((case when x.metric='mean' then avg(s.price) when x.metric='p30' then percentile_cont(.3) within group(order by s.price) when x.metric='p60' then percentile_cont(.6) within group(order by s.price) when x.metric='min' then min(s.price) when x.metric='max' then max(s.price) else percentile_cont(.5) within group(order by s.price) end)::numeric,6),'volume',count(*) filter(where s.sale_month=q.sale_month),'window_volume',count(s.price),'area',round(percentile_cont(.5) within group(order by s.area)::numeric,6),'cycle',round(percentile_cont(.5) within group(order by s.cycle)::numeric,6),'discount',round(percentile_cont(.5) within group(order by s.discount)::numeric,6)) point from months q cross join bounds x left join scoped s on (q.key='全部' or s.district=q.key) and s.sale_month between to_char(to_date(q.sale_month||'-01','YYYY-MM-DD')-make_interval(months=>x.win-1),'YYYY-MM') and q.sale_month group by q.key,q.sale_month,x.metric), trends as (select coalesce(jsonb_object_agg(key,jsonb_build_object('points',p)),'{}'::jsonb) value from (select key,jsonb_agg(point order by sale_month) p from points group by key)a)
  select jsonb_build_object('config',(select raw from bounds),'benchmark',(select value from benchmark),'districts',coalesce((select jsonb_agg(value order by value->>'district') from records where kind='district'),'[]'::jsonb),'communities',coalesce((select jsonb_agg(value order by value->>'district',value->>'business_area',value->>'community') from records where kind='community'),'[]'::jsonb),'map',coalesce((select jsonb_agg(jsonb_build_object('district',district,'price_change',case when cp is not null and bp<>0 then round((cp/bp-1)::numeric,6) end,'current_volume',cv,'base_volume',bv,'eligible',(cv>=minc and bv>=minb and cv+bv>=mint and cp is not null and bp is not null and bp<>0)) order by district) from map_ag cross join bounds),'[]'::jsonb),'trends',(select value from trends)) into out;
  return out;
end $$;

create or replace function public.housing_compute_market(p_params jsonb,p_history jsonb) returns jsonb language sql stable security definer set search_path='' as $$ select housing_private.compute_market(p_params,p_history) $$;
revoke all on function housing_private.compute_market(jsonb,jsonb) from public,anon,authenticated;
revoke all on function public.housing_compute_market(jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.housing_compute_market(jsonb,jsonb) to service_role;
