-- No source transactions, email addresses, credentials or plaintext tokens here.
-- New transactions only. Public history stays in the cutoff-limited Pages build.
create schema if not exists housing_private;
revoke all on schema housing_private from public, anon, authenticated;
alter default privileges in schema housing_private revoke all on tables from public, anon, authenticated;
alter default privileges in schema housing_private revoke execute on functions from public, anon, authenticated;

create table housing_private.communities (
  id bigint generated by default as identity primary key,
  district text not null,
  business_area text not null,
  community text not null,
  unique (district, business_area, community)
);
create table housing_private.transactions (
  id bigint primary key,
  community_id bigint not null references housing_private.communities(id),
  sale_date date not null check (sale_date >= date '2025-09-01'),
  area double precision not null check (area > 0),
  unit_price double precision not null check (unit_price > 0),
  sale_price double precision not null check (sale_price > 0),
  listing_price double precision,
  layout text, rooms text, orientation text, floor text,
  cycle_days integer, discount_rate double precision
);
create index transactions_community_date on housing_private.transactions (community_id, sale_date, id);
create index transactions_date on housing_private.transactions (sale_date);

create table housing_private.accounts (
  user_id uuid primary key references auth.users(id) on delete cascade
);
create table housing_private.trial_unlocks (
  user_id uuid not null references housing_private.accounts(user_id) on delete cascade,
  community_id bigint not null references housing_private.communities(id),
  created_at timestamptz not null default now(),
  primary key (user_id, community_id)
);
create table housing_private.paid_tokens (
  id uuid primary key default gen_random_uuid(),
  order_ref text not null unique,
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  duration_days integer not null check (duration_days between 1 and 3660),
  redeem_before timestamptz not null,
  intended_user_id uuid references auth.users(id),
  redeemed_by uuid references auth.users(id),
  redeemed_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  revoke_reason text,
  check ((redeemed_by is null and redeemed_at is null and expires_at is null)
      or (redeemed_by is not null and redeemed_at is not null and expires_at is not null))
);
create index paid_tokens_user on housing_private.paid_tokens (redeemed_by, expires_at);
-- Bound per-account redemption attempts; increment on invalid codes too.
create table housing_private.redeem_limits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  window_start timestamptz not null,
  attempts integer not null
);

alter table housing_private.communities enable row level security;
alter table housing_private.transactions enable row level security;
alter table housing_private.accounts enable row level security;
alter table housing_private.trial_unlocks enable row level security;
alter table housing_private.paid_tokens enable row level security;
alter table housing_private.redeem_limits enable row level security;
revoke all on all tables in schema housing_private from public, anon, authenticated;
revoke all on all sequences in schema housing_private from public, anon, authenticated;

create function housing_private.verified_uid() returns uuid
language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null or not exists (
    select 1 from auth.users u where u.id = v_uid and u.email_confirmed_at is not null
      and coalesce(u.email, '') <> '' and not coalesce(u.is_anonymous, false)
  ) then
    raise exception 'verified_email_required' using errcode = '42501';
  end if;
  return v_uid;
end;
$$;

create function housing_private.paid_until(p_uid uuid) returns timestamptz
language sql stable security definer set search_path = '' as $$
  select max(expires_at) from housing_private.paid_tokens
  where redeemed_by = p_uid and revoked_at is null and expires_at > now();
$$;

create function public.housing_access() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := housing_private.verified_uid(); v_exp timestamptz;
begin
  v_exp := housing_private.paid_until(v_uid);
  return jsonb_build_object(
    'user_id', v_uid, 'tier', case when v_exp is null then 'registered' else 'paid' end,
    'free_through', '2025-08-31', 'paid_from', '2025-09-01', 'expires_at', v_exp,
    'trial_limit', 2,
    'trial_communities', coalesce((select jsonb_agg(jsonb_build_object(
      'district', c.district, 'business_area', c.business_area, 'community', c.community
    ) order by t.created_at, c.id) from housing_private.trial_unlocks t
      join housing_private.communities c on c.id = t.community_id where t.user_id = v_uid), '[]'::jsonb)
  );
end;
$$;

create function public.housing_claim_trial(p_district text, p_business_area text, p_community text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_uid uuid := housing_private.verified_uid(); v_cid bigint;
begin
  select id into v_cid from housing_private.communities where
    district = p_district and business_area = p_business_area and community = p_community;
  if v_cid is null or not exists (select 1 from housing_private.transactions where community_id = v_cid) then
    return jsonb_build_object('ok', false, 'code', 'no_new_data');
  end if;
  if housing_private.paid_until(v_uid) is not null then
    return jsonb_build_object('ok', true, 'access', public.housing_access());
  end if;
  insert into housing_private.accounts values (v_uid) on conflict do nothing;
  -- Serialize claims for the same account, including simultaneous first claims.
  perform 1 from housing_private.accounts where user_id = v_uid for update;
  if exists (select 1 from housing_private.trial_unlocks where user_id = v_uid and community_id = v_cid) then
    return jsonb_build_object('ok', true, 'access', public.housing_access());
  end if;
  if (select count(*) from housing_private.trial_unlocks where user_id = v_uid) >= 2 then
    return jsonb_build_object('ok', false, 'code', 'trial_exhausted', 'access', public.housing_access());
  end if;
  insert into housing_private.trial_unlocks(user_id, community_id) values (v_uid, v_cid);
  return jsonb_build_object('ok', true, 'access', public.housing_access());
end;
$$;

create function public.housing_redeem(p_token text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare v_uid uuid := housing_private.verified_uid(); v_token housing_private.paid_tokens;
  v_attempts integer;
begin
  insert into housing_private.redeem_limits as r values (v_uid, now(), 1)
  on conflict (user_id) do update set
    attempts = case when r.window_start < now() - interval '1 minute' then 1 else r.attempts + 1 end,
    window_start = case when r.window_start < now() - interval '1 minute' then now() else r.window_start end
  returning attempts into v_attempts;
  if v_attempts > 10 then return jsonb_build_object('ok', false, 'code', 'rate_limited'); end if;
  if p_token is null or length(p_token) not between 40 and 128 then
    return jsonb_build_object('ok', false, 'code', 'invalid_token');
  end if;
  select * into v_token from housing_private.paid_tokens
    where token_hash = encode(sha256(convert_to(p_token, 'UTF8')), 'hex') for update;
  if not found or v_token.revoked_at is not null
      or (v_token.intended_user_id is not null and v_token.intended_user_id <> v_uid)
      or (v_token.redeemed_by is not null and v_token.redeemed_by <> v_uid) then
    return jsonb_build_object('ok', false, 'code', 'invalid_token');
  end if;
  -- Same-account retry cannot extend expiry; already-expired codes cannot reactivate.
  if v_token.redeemed_by = v_uid then
    return jsonb_build_object('ok', v_token.expires_at > now(), 'access', public.housing_access());
  end if;
  if v_token.redeem_before <= now() then return jsonb_build_object('ok', false, 'code', 'invalid_token'); end if;
  update housing_private.paid_tokens set redeemed_by = v_uid, redeemed_at = now(),
    expires_at = now() + make_interval(days => v_token.duration_days) where id = v_token.id;
  return jsonb_build_object('ok', true, 'access', public.housing_access());
end;
$$;

create function public.housing_new_transactions(
  p_district text, p_business_area text, p_community text,
  p_after_date date default null, p_after_id bigint default null, p_page_size integer default 200
) returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare v_uid uuid := housing_private.verified_uid(); v_cid bigint; v_rows jsonb;
begin
  if p_page_size is null or p_page_size not between 1 and 200
    or (p_after_date is null) <> (p_after_id is null) then
    raise exception 'invalid_pagination' using errcode = '22023';
  end if;
  select id into v_cid from housing_private.communities where
    district = p_district and business_area = p_business_area and community = p_community;
  if housing_private.paid_until(v_uid) is null and not exists (
    select 1 from housing_private.trial_unlocks where user_id = v_uid and community_id = v_cid
  ) then raise exception 'community_locked' using errcode = '42501'; end if;
  select coalesce(jsonb_agg(to_jsonb(t) order by t.sale_date, t.id), '[]'::jsonb) into v_rows from (
    select id, sale_date, area, unit_price, sale_price, listing_price,
      case when listing_price > 0 then listing_price * 10000 / area end as listing_unit_price,
      layout, rooms, orientation, floor, cycle_days, discount_rate
    from housing_private.transactions where community_id = v_cid
      and (p_after_date is null or (sale_date, id) > (p_after_date, p_after_id))
    order by sale_date, id limit p_page_size
  ) t;
  return jsonb_build_object('transactions', v_rows, 'access', public.housing_access());
end;
$$;

-- Functions default to PUBLIC execution in PostgreSQL: remove it explicitly.
revoke all on all functions in schema housing_private from public, anon, authenticated;
revoke all on function public.housing_access() from public, anon;
revoke all on function public.housing_claim_trial(text,text,text) from public, anon;
revoke all on function public.housing_redeem(text) from public, anon;
revoke all on function public.housing_new_transactions(text,text,text,date,bigint,integer) from public, anon;
grant execute on function public.housing_access() to authenticated;
grant execute on function public.housing_claim_trial(text,text,text) to authenticated;
grant execute on function public.housing_redeem(text) to authenticated;
grant execute on function public.housing_new_transactions(text,text,text,date,bigint,integer) to authenticated;
